### ISSUE TITLE
希望加入2个国内可访问的域名列表。

### ISSUE THREAD

**Issue by hkthomas** [mouyase/ChinaListForAdGuardHome#4]
https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/apple-cn.txt

https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/google-cn.txt

这两个列表都是国内有节点的，我看国内域名里没有，走国外dns解析非常慢。

能否麻烦加上自动更新行列，谢谢。 :)

**Comment by hkthomas** [comment]
自己已解决。

**Comment by mouyase** [comment]
等有空我优化一下脚本，调一下这个列表
